sonar.projectKey=Projeto-Prisma_prisma-m4-recorrencia
sonar.organization=projeto-prisma

# Caminho do código fonte
sonar.sources=src
sonar.exclusions=**/*.yml, README.md, .github/**/*, testes/**/*

# Configurações do Python
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml