sonar.projectKey=seu-usuario-github_conecta-recife-m4
sonar.organization=sua-organizacao-github

# Caminho do código fonte
sonar.sources=src
sonar.exclusions=**/*.yml, README.md, .github/**/*, testes/**/*

# Configurações do Python
sonar.python.version=3.11